#!/bin/sh

DISPLAYS="$(yabai -m query --displays)"
SPACES="$(yabai -m query --spaces)"
WINDOWS="$(yabai -m query --windows)"

printf '{"displays":%s,"spaces":%s,"windows":%s}\n' "$DISPLAYS" "$SPACES" "$WINDOWS"
